k8-argocd-provisioning:
  appproject:
    name: slaughtered
    description: "Slaughtered Application"
    repositories:
      - https://github.com/kcsoukup/argocd-apps.git
    destinations:
      namespace: pantera
      server: https://kubernetes.default.svc

  application:
    name: slaughtered
    source:
      repoURL: https://github.com/kcsoukup/argocd-apps.git
      path: whatpod
      targetRevision: HEAD
      helm:
        valueFiles:
          - values-pantera.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: pantera
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      retry:
        limit: 3
        backoff:
          duration: "5s"
          factor: 2
          maxDuration: "3m"
